### ISSUE TITLE
past_key_tokens

### ISSUE THREAD

**Issue by arielshaulov** [shreydan/VisionGPT2#1]
Hi,
what if i want to use the ability to pass "past_key_values" to the "GPT2LMHeadModel". can you help me with that ?

**Comment by shreydan** [comment]
hi @arielshaulov, thank you for checking out my work. For 'past_key_values' implementation, I'd recommend going through the HF implementation of GPT2: [modeling_gpt2.py](https://github.com/huggingface/transformers/blob/main/src/transformers/models/gpt2/modeling_gpt2.py) 

Another way to construct this VLM is to use, `VisionEncoderDecoderModel` class from transformers, like this: [nlpconnect/vit-gpt2-image-captioning](https://huggingface.co/nlpconnect/vit-gpt2-image-captioning), which should also give you the ability to pass 'past_key_values'.

thanks!
